DCC-4636. Separate release and submission reports
icgc-dcc/dcc-submission pull request #43
Opened 2016-10-20 15:03 UTC by slovit

2016-10-20 15:18 UTC, btiernay requested changes

2016-10-20 15:18 UTC, btiernay commented on dcc-submission-core/src/main/java/org/icgc/dcc/submission/release/model/ReleaseView.java
> +    for (val submissionState : submissionsStates) {
http://stackoverflow.com/questions/25441088/group-by-counting-in-java8-stream-api:

```java
val summary  = submissionsStates.stream().collect(groupingBy(identity(), counting()));
```

2016-10-20 15:18 UTC, btiernay commented on dcc-submission-server/src/main/java/org/icgc/dcc/submission/server/repository/SubmissionRepository.java
> +        .filter("releaseName == ", releaseName)
Can we use type safe morphia dsl?

2016-10-20 15:18 UTC, btiernay commented on dcc-submission-server/src/main/java/org/icgc/dcc/submission/server/service/ReleaseService.java
> +        .anyMatch(state -> state == SIGNED_OFF);
Predicates#isEqual:`isEqual(SIGNED_OFF)`

2016-10-20 15:18 UTC, btiernay commented on dcc-submission-server/src/main/java/org/icgc/dcc/submission/server/service/ReleaseService.java
> +    val projectKeys = queuedProjects.stream()
Duplicated below. Lets add utility method.

2016-10-20 15:18 UTC, btiernay commented on dcc-submission-server/src/main/java/org/icgc/dcc/submission/server/service/ReleaseService.java
> +    val invalidProjectKeys = submissionService.findSubmissionsByReleaseName(release.getName()).stream()
This is very expensive (submissions are big!). Lets push down the predicate into the query.

2016-10-20 15:18 UTC, btiernay commented on dcc-submission-server/src/test/java/org/icgc/dcc/submission/server/service/ReleaseServiceTest.java
> +@Ignore("Add tests")
Lets remove this and make sure tests still pass.

2016-10-20 16:41 UTC, slovit commented on dcc-submission-server/src/main/java/org/icgc/dcc/submission/server/service/ReleaseService.java
> +    val projectKeys = queuedProjects.stream()
It's a 'getter'. It has no logic.

2016-10-20 16:43 UTC, slovit commented on dcc-submission-server/src/main/java/org/icgc/dcc/submission/server/service/ReleaseService.java
> +        .anyMatch(state -> state == SIGNED_OFF);
What `Predicates`? There's no such a method neither in our commons `Predicates` nor in Guava's.

2016-10-20 16:48 UTC, slovit commented on dcc-submission-server/src/main/java/org/icgc/dcc/submission/server/repository/SubmissionRepository.java
> +        .filter("releaseName == ", releaseName)
I think 'no'. I didn't find how Morphia DSL could be used for DML. It looks like the version we use supports querying only.

2016-10-20 17:43 UTC, btiernay approved these changes

2016-10-21 18:55 UTC, btiernay commented on dcc-submission-server/src/main/java/org/icgc/dcc/submission/server/service/ReleaseService.java
> +        .filter(submission -> submission.getState() == INVALID)
Ah, my bad, sorry for leading you astray here!

2016-10-22 17:35 UTC, btiernay commented on dcc-submission-core/src/main/java/org/icgc/dcc/submission/core/security/Authorizations.java
> +  private static String extractProject(String permission) {
`parseProject`

2016-10-24 14:13 UTC, merged